# Generated by Django 3.0.6 on 2020-05-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='agences', verbose_name='Logo')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name="Code de l'agence")),
                ('name', models.CharField(max_length=250, unique=True, verbose_name="Nom de l'agence")),
                ('owner_name', models.CharField(blank=True, max_length=250, verbose_name='Nom du Propriétaire')),
                ('district', models.CharField(max_length=250, verbose_name='Quartier')),
                ('town', models.CharField(max_length=250, verbose_name='Ville')),
                ('country', models.CharField(max_length=250, verbose_name='Pays')),
                ('address', models.CharField(max_length=250, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=250, verbose_name="Email de l'agence")),
                ('phone', models.CharField(max_length=250, verbose_name="Téléphone  de l'agence")),
                ('description', models.TextField(blank=True, verbose_name="Description  de l'agence")),
                ('email_owner', models.EmailField(blank=True, max_length=250, verbose_name='Email du Propriétaire')),
                ('phone_owner', models.CharField(blank=True, max_length=250, verbose_name='Téléphone du Propriétaire')),
                ('website', models.CharField(blank=True, max_length=250, verbose_name="Site Web  de l'agence")),
                ('status', models.CharField(choices=[('Déjà crée', 'Déjà crée'), ('En création', 'En création')], default='Déjà crée', max_length=250, verbose_name="Statut Actuel  de l'agence")),
                ('open_days', models.CharField(max_length=250, verbose_name='Jours Ouverts')),
                ('closed_days', models.CharField(max_length=250, verbose_name='Jours Fermés')),
                ('discount', models.IntegerField(blank=True, default='0', verbose_name='Remise')),
                ('notes', models.IntegerField(blank=True, default='0', verbose_name='Notes')),
                ('code_promo', models.CharField(blank=True, max_length=250, verbose_name='Code Promo')),
                ('longitude', models.CharField(blank=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(blank=True, default='0.0', max_length=100)),
                ('services', models.CharField(choices=[('Voyage Terrestre', 'Voyage Terrestre'), ('Voyage Ferroviaire', 'Voyage Ferroviaire'), ('Voyage Maritime', 'Voyage Maritime'), ('Voyage Aérien', 'Voyage Aérien')], default='Espèces, Carte de crédit...', max_length=250, verbose_name='Nos Services')),
                ('payment_method', models.CharField(choices=[('Espèces', 'Espèces'), ('Carte de crédit', 'Carte de crédit'), ('Mobile Money', 'Mobile Money'), ('Espèces, Carte de crédit...', 'Tout')], default='Espèces, Carte de crédit...', max_length=250, verbose_name='Paiement Accepté')),
                ('terms', models.BooleanField(verbose_name='Termes & Conditions')),
                ('connected', models.CharField(choices=[('En ligne', 'En ligne'), ('Hors ligne', 'Hors ligne')], default='Hors ligne', max_length=250, verbose_name='Ouvert ou Fermé ?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
            options={
                'verbose_name': 'agence',
                'verbose_name_plural': 'agences',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Libellé')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, upload_to='engins', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
            options={
                'verbose_name': 'engin',
                'verbose_name_plural': 'engins',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TypeVoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Libellé')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, upload_to='type_voyages', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'type de voyage',
                'verbose_name_plural': 'types de voyage',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Réference')),
                ('date_depart', models.DateField(verbose_name='Date Départ')),
                ('date_arrivee', models.DateField(verbose_name='Date Arrivée')),
                ('heure_depart', models.TimeField(verbose_name='Heure Départ')),
                ('heure_arrivee', models.TimeField(verbose_name='Heure Arrivée')),
                ('ville_depart', models.CharField(max_length=250, verbose_name='Ville Départ')),
                ('ville_arrivee', models.CharField(max_length=250, verbose_name='Ville Arrivée')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nbre_places', models.IntegerField(verbose_name='Nombre de Places')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', models.ImageField(blank=True, upload_to='voyages', verbose_name='Photo')),
                ('available', models.BooleanField(default=True, verbose_name='Disponibilité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Agence', verbose_name='Agence')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Engin', verbose_name='Engin')),
                ('typevoyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.TypeVoyage', verbose_name='Type de Voyage')),
            ],
            options={
                'verbose_name': 'voyage',
                'verbose_name_plural': 'voyages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.TimeField(verbose_name='Heure Arrivée')),
                ('heure_depart', models.TimeField(verbose_name='Heure Départ')),
                ('ville_arrivee', models.CharField(max_length=250, verbose_name='Ville Arrivée')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'escale',
                'verbose_name_plural': 'escales',
                'ordering': ('voyage',),
            },
        ),
        migrations.CreateModel(
            name='ClasseVoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Libellé')),
                ('slug', models.SlugField(max_length=250, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Adulte')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Enfant')),
                ('nbre_places_classe', models.IntegerField(verbose_name='Nombre de Places')),
                ('stock_classe', models.IntegerField(verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'classe voyage',
                'verbose_name_plural': 'classes voyage',
                'ordering': ('name',),
            },
        ),
    ]
